#!/usr/bin/env node

// Check args
if ( process.argv.length != 7 ) {
	console.log('USAGE: rdptest [domain] [user] [pass] [ip] [port]');

	process.exit(1);
}

var rdp = require('node-rdpjs');

var connectHits = 0;

// 1 second timeout for login
var cfg_timeout = 1000;

var arg_domain = process.argv[2],
    arg_username = process.argv[3],
    arg_password = process.argv[4],
    arg_ip = process.argv[5],
    arg_port = process.argv[6];

var client = rdp.createClient({
	domain: arg_domain,
	userName: arg_username,
	password: arg_password,
	enablePerf: true,
	autoLogin: true,
	decompress: false,
	screen: {
		width: 800,
		height: 600
	},
	local: 'en',
	logLevel: 'ERROR'
})
.on('connect', function() {
	connectHits++;
	
	// We logged in
	if ( connectHits == 2 ) {
		console.log('Login successful');

		// Close the connection
		client.close();

		// Exit gracefully
		process.exit(0);
	}
})
.on('close', function() {
	// Do nothing...
})
.on('error', function(err) {
	// We don't care about your errors!
})
.connect(arg_ip, arg_port);

// Set timeout so we don't wait too long
setTimeout(function() {
	// We haven't connected yet...
	if ( connectHits != 2 ) {
		client.close();

		if ( connectHits == 0 ) {
			console.log('Failed to connect - timeout in contacting server');
		} else {
			console.log('Failed to connect - possible invalid creds');
		}

		process.exit(1);
	}
}, cfg_timeout);
